<span><b>Thanks for your email. I'll get back to you ASAP.</b></span>
<?
  // include the PEAR mail class
  include 'Mail.php';

  // set up the recipient and necessary headers
  $recipients = 'Justin Gitlin <cacheflowe@cacheflowe.com>';
  $headers['From']    = $_POST['email'];
  $headers['To']      = 'Justin Gitlin';
  $headers['Subject'] = $_POST['about'];

  // piece together the body message
  $body = "This message was generated by ".$_SERVER['SERVER_NAME']."\nfrom: ".$_POST['email']."\nmessage: ".$_POST['message'];

  // Create the mail object and send it!
  $mail_object = Mail::factory('mail', $params);
  $mail_object->send($recipients, $headers, $body);
?>
